# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d3f313ec173481536528262b8e0109cef41971218885912045b0bfd72be6c3d063de87662a930d8db0ba24a2854e9b66c396591c8df39babed0615803413f3

test:
  secret_key_base: 44c377d4ec983a1d6e2cf1f6abfb4768970d402cf787806e8970959ee49ad08be76aad609e3976f102438f00285fd39741d793d148950487c68ce5056b9a572a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
